Update .gitignore
tfiedor/perun pull request #122
Opened 2023-10-06 21:24 UTC by HarryMichal

This is a combination of GitHub's .gitignore's for Python[0] and JetBrains[1].

[0] https://github.com/github/gitignore/blob/main/Python.gitignore
[1] https://github.com/github/gitignore/blob/main/Global/JetBrains.gitignore

2023-10-25 19:05 UTC, tfiedor requested changes
I think the new `.gitignore` is good (I guess generated by some tool), but I would squash the idea directories (and maybe, if there are more similar cases that I overlooked, I would squash them as well; I'd rather keep the stuff short and concise).

2023-10-25 19:05 UTC, tfiedor commented on .gitignore
> +.idea/**/workspace.xml
Please, lets merge this to `.idea/**` or `.idea/*`. I don't think there is valid reason for not ignoring anything related to IDEs.

2023-10-26 10:06 UTC, JiriPavela commented on .gitignore
> +.idea/**/workspace.xml
I agree. There is an explanation (in the long comment just above the shown snippet) of why the .idea ignores are scattered like that, but I think ignoring the entire .idea shouldn't really introduce any problem.

2023-10-26 10:08 UTC, HarryMichal commented on .gitignore
> +.idea/**/workspace.xml
Done.

2023-10-26 10:10 UTC, tfiedor approved these changes

2023-10-26 11:14 UTC, JiriPavela approved these changes

2023-10-26 11:18 UTC, merged